- name: Run database container
  docker_container:
    name: database
    image: wardkhalife/tp-devops-database:latest
    env:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    networks:
      - name: my_network
    state: started
    restart_policy: always