- name: Run front container
  community.docker.docker_container:
    name: front
    image: wardkhalife/front:latest
    state: started
    restart_policy: always
    networks:
      - name: my_network
    ports:
      - "3000:80"
    pull: true
    recreate: true
