- name: Run API container
  docker_container:
    name: simple-api
    image: wardkhalife/tp-devops-simple-api:latest
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/db
      SPRING_DATASOURCE_USERNAME: usr
      SPRING_DATASOURCE_PASSWORD: pwd
    networks:
      - name: my_network
    ports:
    - "8080:8080"
    state: started
    restart_policy: always
    recreate: true
