- name: Run proxy container
  docker_container:
    name: proxy
    image: wardkhalife/tp-devops-httpd:latest
    ports:
      - "80:80"
    networks:
      - name: my_network
    state: started
    restart_policy: always